# -*- coding: utf-8 -*-
"""Mastering_Data_Wrangling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PpFGbZo4sNFSDAnEdIhmSkUh7-k1x6LF
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

!ls /content/drive/MyDrive/Dvdrental

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Dvdrental/customer.csv')
print(df.head())

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Dvdrental/customer.csv')
print(df.head())
print(df.shape)
print(df.tail())
df.columns
df.info()
df.describe()

df.duplicated().sum()

# Checking and Removing Duplicates
df.duplicated().sum()
df_no_dup = df.drop_duplicates()

df_no_dup.shape

# Handling Missing Values
df.isnull().sum()
df_clean = df.dropna()
df_clean.shape

df_filled = df.fillna("unknown")
df_filled.shape
df_filled.head()
df_filled.isnull().sum()
df_filled[df_filled=="unknown"]

# Fetching Columns Without Using loc and iloc
df["first_name"].head()
df_subset = df[["first_name", "last_name"]]
df_subset.head()

# Filtering Using loc and iloc
df_loc = df.loc[df["store_id"] ==1,["first_name", "last_name","email"]]
df_loc.head()

df_iloc = df.iloc[:5,[0,2,3]]
df_iloc

# Sorting Data
df_sorted = df.sort_values(by = "customer_id", ascending=False)
df_sorted
df_sorted.head()

df_renamed = df.rename(columns = {"first_name":"Cx_first_name"})
df_renamed.head()

df_replaced = df.replace({"store_id" : {1 :"store_id_A", 2:"store_id_B"}})
df_replaced.head()

# creating Columns
df["Full_Name"] = df["first_name"] + " " + df["last_name"]
df.head()

df_filtered = df[df["store_id"]== 1]
df_filtered.shape

df_filtered = df.query("store_id ==1 and customer_id ==1")
df_filtered.head()