# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fahVf9gzzym5K414_gmRpE3vlyT3gFBc
"""

# Packages and Modules
# Packages/ library is a collection of modules & modules is a single file containing Python definitions and statements.

"""#Numpy(Numerical Python)
* It is the library used for mathematical computations & data analysis*
* used for creating arrays & matrices
* It also helps in solving complex problems like linear algebra , fourier transforms, matrix related problems
* it is also used to solve problems related to Datascience , ML & AI.
* Image Processing , Audio , video

# what can be done with numpy?
* Create arrays to store values
* We can generate arrays using inbuilt functions
* Indexing & Slicing
* Mathematical operations & statistical, Mathematical fnx.
* matrix multiplication , finding determinant , inverse , eigen values
"""

# import the libraries
import numpy as np

# create an array to store 100
arr = np.array(100)
arr1 = np.array((10,20, 30, 40, 50))
arr2 = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr1)
print( arr2)
print("type is ", type(arr1))
print("size is ", arr1.size)
print("shape is ", arr1.shape)
print("dimension is ", arr1.ndim)
print("dtype is ", arr1.dtype)

"""# Functions & Method
* size : used to find the length of array
* type : used to find the type of object
* dtype : used to find the data type of object
* shape : it gives the no. of rows & columns
* ndm : it is used to find the dimensions of an array
"""

A = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(A)
print(matrix)
print("type is ", type(matrix))
print("size is ", matrix.size)
print("shape is ", matrix.shape)
print("dimension is ", matrix.ndim)
print("dtype is ", matrix.dtype)

# size = no. of rows * no. of columns

# np.arange - creates evenly space values
np.arange(1,10,2)

#np.reshape - Reshapes an array into a new shape without changing its data
arr1 = np.arange(1,10)
print(arr1)
arr2 = arr1.reshape(3,3)
print(arr2)

#np.flatten - convert multi dimensional array into 1d
arr3 = arr2.flatten()
print(arr3)

arr4 = arr2.transpose()
print(arr4)

sorted_arr = np.array([1,2,3,9,6,5,4])
print(sorted_arr)
sorted_arr.sort()
print(sorted_arr)

"""Numpy Math functions
* sum()
* min()
* max()
* std()
* mean()
"""

arr_math = np.array([10,20,30,40,50])
print(arr_math)
print(np.min(arr_math))
print(np.max(arr_math))
print(np.std(arr_math))
print(np.sum(arr_math))
print(np.mean(arr_math))
print(np.median(arr_math))

# indexing & slicing in numpy
arr_2d = [[1,2,3],[4,5,6]]
arr_2d = np.array(arr_2d)
print(arr_2d)
print(arr_2d[1,2])
print(arr_2d[:,2])
print(arr_2d[1,:])

"""# Pandas
* Pandas is a powerful library for handling structured data
* used for data analysis , integration with sql & data manipulation

"""

# Pandas Series - used to create 1d array
import pandas as pd
data = pd.Series([10,20,30,40,50])
data

# dataframe - used to create 2 dim. array , similar to table
data_frame = pd.DataFrame({
    "name" : ["om", "shivay", "Rudra"],
    "marks" : [10, 20, 30]
})
print(data_frame)

"""# Creating DataFrame from Different Data Structures"""

# from list
df = pd.DataFrame([[101,"Mohini"],[102,"vanshika"], [103,"shalini"]])
columns = ["ID", "NAME"]
df

#from dictionaries
df = pd.DataFrame({'ID': [101 , 102,103],'NAME' : ["JESSICA" , "vanshi", "shalVI"]})
df

# from npArray
arr = np.array([[101,"Mohini"],[112,"vanshika"], [103,"shalini"]])
df_array = pd.DataFrame(arr, columns=['ID', 'Name'])
df_array