# -*- coding: utf-8 -*-
"""Numpy01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJgjfBZHbzeQwwNwqtEUxI8JlPTUpojC
"""

#APPLICATIONS
# powerful N - dimensional array object
# broadcasting functions
# tools for integrating C/C++ and Fortran code
# useful linear algebra, Fourier transform, and random number capabilities

#creating Numpy n-d arrays
import numpy as np
arr = np.array([1,2,3,4,5])
arr

type(arr)

arr1 = np.array([[1,23,4],[5,6,7]])
arr1

arr3 = np.zeros((2,3))
arr3

arr4 = np.ones((3,3))
arr4

arr2 = np.identity(5)
arr2

arr5 = np.arange(10)
arr6 = np.arange(5,10)
arr7 = np.arange(5,10,2)
arr5
arr6
arr7

arr8 = np.linspace(10,20,5)
arr8

arr9 = arr8.copy()
arr9

"""## Numpy Array Properties & Attributes"""

arr1.shape

arr10 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr10

arr10.shape

arr10.ndim

arr2.ndim

arr.ndim

arr.size

arr10.size      #how many elements in the array

arr10.itemsize        # how much bytes consume like float consumes 8 bytes

arr8.dtype

arr10.dtype

arr10.astype(float)

arr10.astype(str)

"""##Numpy Array Vs Lists"""

list = range(100)
arr12 = np.arange(100)

"""Python lists store references to objects, and each element is a separate object with additional memory overhead. In contrast, NumPy arrays store elements in a contiguous block of memory with a fixed data type, reducing overhead and making them more memory-efficient."""

import sys

print(sys.getsizeof(87)*len(list)) # Memory used by Python list

print(arr12.itemsize*arr12.size) # Memory used by NumPy array

import time

x = range(10000000)
y = range(10000000,20000000)
start_time = time.time()
c = [(x,y) for x,y in zip(x,y)]
print(time.time()- start_time)

a = np.arange(10000000)
b = np.arange(10000000, 20000000)
start_time = time.time()
c = a+b
print(time.time()- start_time)

"""## Indexing , Slicing & Iteration"""

ar = np.arange(24).reshape(6,4)
ar

ar[:,1:3]

ar[2:4,1:3]
ar

for i in ar:
  print(i)

for i in np.nditer(ar):
  print(i)

"""##Numpy Array Operations"""

a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6,7,8,9])

a-b

a*b

a+b

a*2

a>3

arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)
arr3.dot(arr4)

arr4.max()

arr4.min(axis=0)

arr4.min(axis=0)  # axis = 0 → move vertically (↓) → operate on columns

arr4.min(axis=1)  # axis = 1 → move horizontally (→) → operate on rows

arr4.sum(axis= 0)

arr4.sum(axis=1)

arr4.std()

np.sin(arr4)

np.median(arr4)

np.exp(arr4)

arr4.ndim

arr4.ravel()      #convert higher dimensional function into 1d array

arr4

arr4.transpose()

arr3

arr5= np.arange(12,18).reshape(2,3)
np.hstack((arr3,arr5))

"""##Stacking



"""

np.vstack((arr3,arr5))

np.hsplit(arr3,3)

"""👉 h → height stays same → columns split ,,,,
👉 v → vertical stacking → rows split
"""

np.vsplit(arr3,2)

"""## Fancy Indexing in Numpy"""

arr8 = np.arange(12).reshape(3,4)
arr8

arr8[[0,2]]

"""## Indexing With Boolean Arrays



"""

arr = np.random.randint(low=1, high=100,size=20).reshape(4,5)
arr

arr[0]

arr[arr>50]

arr[(arr>50)& (arr%2!=0)]

arr[(arr>50)& (arr%2!=0)] = 0

arr

x = np.linspace(-40,40,100)
x.size

y=np.sin(x)
y.size

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.plot(x,y)

y = x*x+2*x+6
plt.plot(x,y)

a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)
a1
a2

a1

a1+a2

a3 = np.arange(9).reshape(3,3)
a4 = np.arange(3).reshape(1,3)
print(a3,a4)

"""##🔹 Broadcasting

👉 Broadcasting means:

NumPy automatically expands smaller arrays to match bigger ones

👉 Rules (remember this order):

Compare shapes from right to left
Each dimension must be:
Same size ✅ OR
One of them is 1 ✅
Otherwise ❌ error
Missing dimensions are treated as 1
Dimension with 1 gets stretched

👉 One-line memory trick:

“Same or 1 → OK, else → Error”
"""

a3+a4             #broadcasting

a7 = np.arange(4).reshape(4,1)
a8 = np.arange(12).reshape(4,3)
a8+a7

var1 = np.array([1,2,3,4])            #same dimension
var2 = np.array([[1],[2],[3],[4]])
print()
print(var1)
print(var1.shape)
print(var2.shape)
print(var2)
print()
print(var1+var2)

x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)
print(x+y)

import numpy as np

# Case 1: Scalar broadcasting
a = np.array([1, 2, 3])
print("Scalar broadcasting:", a + 10)
# 10 becomes [10,10,10]

# Case 2: Different dimensions
A = np.array([[1], [2], [3]])   # shape (3,1)
B = np.array([10, 20, 30, 40])  # shape (4,)

print("\nShapes before broadcasting:")
print("A shape:", A.shape)
print("B shape:", B.shape)

# Broadcasting happens here
result = A + B

print("\nResult after broadcasting:")
print(result)

# Explanation:
# A expands column-wise → (3,4)
# B expands row-wise → (3,4)

# Case 3: Higher dimension
C = np.ones((2,3,1))   # shape (2,3,1)
D = np.array([1,2,3])  # shape (3,)

print("\nBroadcasting in higher dimension:")
print("Result shape:", (C + D).shape)
# Final shape will be (2,3,3)

# Case 4: Broadcasting FAIL
E = np.ones((3,4))
F = np.ones((2,4))

# This will give error
# print(E + F)

print("\nFail case: (3,4) + (2,4) ❌ not possible")

"""## Numpy Functions"""

np.random.random()

np.random.seed(1)
np.random.random()

np.random.uniform(3,10)

np.random.uniform(1,100,10).reshape(5,2)

a = np.random.randint(1,5)

a = np.random.randint(1, 50, 6) # Generate an array instead of a single integer
a[np.argmin(a)]

a = np.random.randint(1,50,6)
a

np.where(a%2==0,-1,a)

a

a = np.random.randint(1,50,10)
a

a = np.sort(a)
a

np.percentile(a,25)

np.percentile(a,50)

np.percentile(a,100)

listArray = np.array([[1,2,3],[5,6,7],[0,3,1]])
listArray

listArray.size
listArray.shape
listArray.dtype

np.array({34,23,23})

zeroes = np.zeros((9,5))
zeroes
zeroes.dtype

rng = np.arange(15)
rng

lspace = np.linspace(1,50,10)
lspace

emp = np.empty((4,6))
emp

emp_like = np.empty_like(lspace)
emp_like

ide = np.identity(45)
ide.shape

arr = np.arange(99)
arr

arr.reshape

arr.ravel()

arr.shape

x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

ar.sum(axis =0)

ar.sum(axis =1)

ar.T

ar.flat

for item in ar.flat:
  print(item)

ar.ndim

ar.size

ar.nbytes

one = np.array([1,2,4,5,54])
one.argmax()

one.argmin()

one.argsort(axis =0)

np.sqrt(one)

one*one

np.count_nonzero(ar)

import sys
ch_ar = [0,4,55,2]
np_ar = np.array(ch_ar)
sys.getsizeof(1)*len(ch_ar)
np_ar.itemsize*np_ar.size
np_ar.tolist()