# -*- coding: utf-8 -*-
"""Pandas_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxLb4DNXleTXpeO7EYJtco6Rc1NOQKKT
"""

import pandas as pd

sales = pd.Series([2,3,5])
sales[1]
sales[0:2]

sales.index

sales.values

sales.dtype

#methods
sales.head(2)
sales.tail(1)
sales.sort_values()

marks = pd.Series([12,90,101,0,15,1])
marks.sort_values()
marks.count()
marks.isnull()
marks.notnull()

#operatios
marks +1
marks*2

marks**2

sales_missing = pd.Series([10,12,1,0,None, 5, 20])
sales_missing.isnull()

sales_missing = sales_missing.fillna(0)

sales_missing

si = pd.Series(data = [100,200,300,400,500], index=list('abcde'))
si

#Pandas DataFrame
data = pd.DataFrame({
    'Name' : ['Ana', 'Enna','Lovika','rishika'],
    'Marks' : [89,50,90,42]
})
data

s1 = pd.Series(data = [100,200,300,400,500], index=list('abcde'))
s1

s2 = pd.Series(data = [10,20,30,40,50], index=list('abcde'))
s2

data = pd.DataFrame({'c1':s1,'c2':s2})
data

import pandas as pd
s1 = pd.Series(data = [100,200,300,400,500], index=list('abcde'))
s1.shape

s2 = pd.Series(data = [10,20,0,40,550], index=list('abcde'))

data = pd.DataFrame({'c1':s1,'c2':s2})
data
data.shape
data.columns
data.dtypes
data.index

#accessing data

#using labels
data.loc['a','c1']
#using index location
# data.iloc[0]
data.iloc[1,1]

data.loc['a','c1']

data.loc['b','c1']

# data.iloc['a','c1'] this will gives error because label mentioned here
data.iloc[0,0]    # now use indexing

data.head()

data.tail(3)

data.count()

data.info()

data.describe()

data.sort_values('c2')

data[data['c2']>50]  #filtering a data
data[data['c1']==200]

#adding , updating & deleting
data['c3'] = [1,2,3,4,5]
data

del data['c3']
data

data = data.drop(columns = ['c2'])
data

data['c2'] = [1,2,3,4,5]
data

data.loc[data['c2']== 2] = 10
data

data.rename(columns={'c1':'column1'},inplace = True)
data