# -*- coding: utf-8 -*-
"""Pandas02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uee8aLd89eCrWwnhSUuiL2UZxsCLuYe
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
df = pd.read_csv('/content/drive/MyDrive/Data_sets/matches - matches.csv')
df

type(df)

!ls /content/drive/MyDrive/Data_sets/

!ls /content/drive/MyDrive/

df.head()

df.tail()

df.shape

df.info()

df.describe()     #summary statistics

df['winner']

df[['team1','team2','winner']]
df[['team1','team2','winner']].shape

#row fetch
df.iloc[1:3]   # start included stop excluded
df.iloc[[1,5,7]]

#fetch row , column
df.iloc[:,1:3]

#filtering dataframe based on a given condition
mask = df['city']== 'Hyderabad'
df[mask].shape[0]

def get_city_match_count(city):
  mask = df['city']== 'city'
  return df[mask].shape[0]

get_city_match_count('Hyderabad')

mask1 = df['city'] =='Hyderabad'
mask2 = df['date']>'2010-01-01'
df[mask1 & mask2].shape[0]

df['winner'].value_counts()

# The Pandas Plot()
import matplotlib.pyplot as plt
df['winner'].value_counts().head().plot(kind='barh')

df['toss_decision'].value_counts().plot(kind='pie')
# categorical values representation - pie, bar

# numerical values representation - histogram
df['win_by_runs'].plot(kind='hist')

myseries = df['winner'].value_counts()
myseries

myseries.index

myseries.values

myseries.tail(4)

myseries['Rising Pune Supergiant']

df['team1'].value_counts()

df['team2'].value_counts()

df['team2'].value_counts()+df['team1'].value_counts()

(df['team2'].value_counts()+df['team1'].value_counts()).sort_values(ascending=False,inplace=True)

df.sort_values('city')

df.sort_values(['city', 'date'],ascending=[True,False])

df.drop_duplicates(subset=['city'])
df.drop_duplicates(subset=['city','season']).shape

df.drop_duplicates('season',keep='last')

!ls /content/drive/MyDrive/Data_sets/

company = pd.read_csv('/content/drive/MyDrive/Data_sets/Fortune 500 Companies US.csv', encoding='latin1')
company

company.head(2)

cities = df.groupby('city').size()
cities

len(df)

cities.sort_values(ascending=False)

cities.head(1)

cities.sum()

cities.mean()

ipl = pd.read_csv('/content/drive/MyDrive/Data_sets/deliveries.csv')
ipl

ipl.head(2)

runs = ipl.groupby('batsman')
runs
runs.get_group('V Kohli')
runs.get_group('V Kohli').shape

runs['batsman_runs'].sum().sort_values(ascending=False).head(5)

mask = ipl['batsman_runs']==4
new_ipl = ipl[mask]
new_ipl

ipl.shape[0]

new_ipl.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(5)

new=ipl[ipl['batsman']== 'v kohli']
new

#isin()
#find most destructive death over batsman in the history of ipl
#strike rate = (no. of runs/ no. of balls)/100
#min batsman 200 balls in over 16-20

mask3 = ipl['over']>15
new_mask = ipl[mask3]
new_mask

all_batsman = new_mask.groupby('batsman')['batsman_runs'].count()
x= all_batsman>200
batsman_list = all_batsman[x].index.tolist()
batsman_list

a = ipl[ipl['batsman'].isin(batsman_list)]
a

df1 = pd.DataFrame({"customer_id":[1,2,3], "first_name" : ["alice", "bob", "charlie"]})
df2 = pd.DataFrame({"customer_id":[2,3,4], "last_name" : ["smith", " yadav", "kumar"]})
df_merge = pd.merge(df1,df2, on="customer_id", how = 'inner')
df_merge

df1 = pd.DataFrame({"customer_id":[1,2,3], "first_name" : ["alice", "bob", "charlie"]})
df2 = pd.DataFrame({"customer_id":[2,3,4], "last_name" : ["smith", " yadav", "kumar"]})
df_merge = pd.merge(df1,df2, on="customer_id", how = 'outer')
df_merge

df1 = pd.DataFrame({"customer_id":[1,2,3], "first_name" : ["alice", "bob", "charlie"]})
df2 = pd.DataFrame({"customer_id":[2,3,4], "last_name" : ["smith", " yadav", "kumar"]})
df_merge = pd.merge(df1,df2, on="customer_id", how = 'left')
df_merge

df1 = pd.DataFrame({"customer_id":[1,2,3], "first_name" : ["alice", "bob", "charlie"]})
df2 = pd.DataFrame({"customer_id":[2,3,4], "last_name" : ["smith", " yadav", "kumar"]})
df_merge = pd.merge(df1,df2, on="customer_id", how = 'right')
df_merge

data = pd.DataFrame({'store_id':[1,1,2,2,3], "revenue": [10, 90,200, 300, 400]})
print(data.groupby('store_id')['revenue'].sum())